services:
  nest-boilerplate-mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    volumes:
      - ./volume/mysql:/var/lib/mysql
